version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
environment:
  matrix:
  - GENERATOR: 'Visual Studio 10'
    PYTHON: 'C:\Python27\python.exe'
  - GENERATOR: 'Visual Studio 10 Win64'
    PYTHON: 'C:\Python27-x64\python.exe'
  - GENERATOR: 'Visual Studio 10'
    PYTHON: 'C:\Python33\python.exe'
  - GENERATOR: 'Visual Studio 10 Win64'
    PYTHON: 'C:\Python33-x64\python.exe'
  - GENERATOR: 'Visual Studio 10'
    PYTHON: 'C:\Python34\python.exe'
  - GENERATOR: 'Visual Studio 10 Win64'
    PYTHON: 'C:\Python34-x64\python.exe'
  - GENERATOR: 'Visual Studio 14'
    PYTHON: 'C:\Python35\python.exe'
  - GENERATOR: 'Visual Studio 14 Win64'
    PYTHON: 'C:\Python35-x64\python.exe'
  - GENERATOR: 'Visual Studio 14'
    PYTHON: 'C:\Python36\python.exe'
  - GENERATOR: 'Visual Studio 14 Win64'
    PYTHON: 'C:\Python36-x64\python.exe'

cache:
  - libgit2-vs10-64 -> libgit2\.git\HEAD
  - libgit2-vs10 -> libgit2\.git\HEAD
  - libgit2-vs14-64 -> libgit2\.git\HEAD
  - libgit2-vs14 -> libgit2\.git\HEAD

init:
- cmd: |
    %PYTHON% -m pip install -U nose wheel
    git clone --depth=1 -b maint/v0.26 https://github.com/libgit2/libgit2.git libgit2

build_script:
- cmd: |
    IF "%GENERATOR%"=="Visual Studio 10 Win64" ( SET LIBGIT2_NAME=libgit2-vs10-64 )
    IF "%GENERATOR%"=="Visual Studio 10" ( SET LIBGIT2_NAME=libgit2-vs10 )
    IF "%GENERATOR%"=="Visual Studio 14 Win64" ( SET LIBGIT2_NAME=libgit2-vs14-64 )
    IF "%GENERATOR%"=="Visual Studio 14" ( SET LIBGIT2_NAME=libgit2-vs14 )


    set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\%LIBGIT2_NAME%\libgit2
    
    IF EXIST %LIBGIT2_NAME% GOTO SKIP_LIBGIT_BUILD
    
    mkdir %LIBGIT2_NAME%
    cd %LIBGIT2_NAME%
    cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
    cmake --build . --config Release --target install
    cd ..
    
    :SKIP_LIBGIT_BUILD
    
    IF "%GENERATOR%"=="Visual Studio 10 Win64" ( call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" )
    
    "%PYTHON%" setup.py bdist_wheel
    
    cp %LIBGIT2_NAME%\Release\git2.dll .
test_script:
- ps: |
    &$env:PYTHON setup.py nosetests --with-xunit
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))

artifacts:
- path: dist\*.whl
