version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
environment:
  matrix:
  - ARCH: 32
    GENERATOR: 'Visual Studio 10'
    PYTHON: 'C:\Python33\python.exe'
    PIP: 'C:\Python33\Scripts\pip.exe'
  - ARCH: 64
    GENERATOR: 'Visual Studio 10 Win64'
    PYTHON: 'C:\Python33-x64\python.exe'
    PIP: 'C:\Python33-x64\Scripts\pip.exe'
  - ARCH: 32
    GENERATOR: 'Visual Studio 10'
    PYTHON: 'C:\Python34\python.exe'
    PIP: 'C:\Python34\Scripts\pip.exe'
  - ARCH: 64
    GENERATOR: 'Visual Studio 10 Win64'
    PYTHON: 'C:\Python34-x64\python.exe'
    PIP: 'C:\Python34-x64\Scripts\pip.exe'
  - ARCH: 32
    GENERATOR: 'Visual Studio 14'
    PYTHON: 'C:\Python35\python.exe'
    PIP: 'C:\Python35\Scripts\pip.exe'
  - ARCH: 64
    GENERATOR: 'Visual Studio 14 Win64'
    PYTHON: 'C:\Python35-x64\python.exe'
    PIP: 'C:\Python35-x64\Scripts\pip.exe'
init:
- cmd: '%PIP% install nose wheel'
build_script:
- cmd: |
    set LIBGIT2=%APPVEYOR_BUILD_FOLDER%\build\libgit2
    git clone --depth=1 -b maint/v0.24 https://github.com/libgit2/libgit2.git libgit2
    mkdir build
    
    cd build
    cmake -DSTDCALL=OFF -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX="%LIBGIT2%" ../libgit2 -G "%GENERATOR%"
    cmake --build . --config Release --target install
    cd ..
    
    IF "%GENERATOR%"=="Visual Studio 10 Win64" ( call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" )
    
    "%PYTHON%" setup.py bdist_wheel 
    "%PIP%" install .
test_script:
- ps: |
    cp build\Release\git2.dll .
    &$env:PYTHON setup.py nosetests --with-xunit
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))

artifacts:
- path: dist\*.whl
